import React, { useEffect, useRef, useState } from "react";
import { motion, useSpring } from "framer-motion";
import arms from "../assets/arms/index.js";
import hats from "../assets/hats/index.js";
import shoes from "../assets/shoes/index.js";
import egg from "../assets/egg.jpg";
import wheat from "../assets/wheat.jpg";
import './Style.css'
import Accessories from "../Accessories/index.js"
import API from '../../utils/API';
import {
    useNavigate
} from "react-router-dom";


export default function Homepage(props) {
    let navigate = useNavigate();

    const savedToken = localStorage.getItem("token");
    if (!savedToken) {
        navigate('/login', { replace: true })
    }

    const windowdim = useRef(null);

    const userSelectedArms = arms.beer
    const userSelectedHat = hats.spinny
    const userSelectedShoes = shoes.slides

    const userHat = userSelectedHat
    const userArms = userSelectedArms
    const userShoes = userSelectedShoes

    // let [loggedInData, setLoggedInData] = useState();
    // useEffect(()=> {
    //     setLoggedInData(userObj)
    //     console.log("LOGGED IN DATA", loggedInData)
    // }, [])

    let [userData, setUserData] = useState({
        id: '',
        username: '',
        eggs: props.loggedInData.eggs,
        chicken: {
            name: ''
        }
    });
    useEffect(() => {
        // console.log("data data", props.loggedInData)
        API.getOneUser(props.loggedInData.id).then((data) => {
            // console.log("data data", data)
            if (data.username) {
                setUserData({
                    id: data.id,
                    username: data.username,
                    eggs: data.eggs,
                    chicken: {
                        name: data.Chicken.chicken_name
                    }
                })
            }
        })

    }, [])


    // const egg var with src
    // create a state variable that holds your array of eggs currently on the page
    // in your useeffect thats adding eggs, you will push one new egg into that array 
    //element in your return (img tag) dynamically generated by mapping your egg array 
    // click event -- event.target to identify the key of the egg -- pop outta your array and delete the element 

    // const egg = new Image();
    // egg.src = '../assets/egg.jpg';
    // const wheat = new Image();
    // wheat.src = '../assets/wheat.jpg';

    // const [eggArr, setEggs] = useState([]);
    const spawnEgg = (event) => {
        event.target.src="";
    }

    // const spawnFood = (event) => {
    //     event.target.src={wheat};
    // }

    function spawnFood() {
        document.getElementById("wheaties").setAttribute("src", wheat)
    }

    // let isFed = false;
    // let [eggCount, setCount] = useState(0);
    // if(isFed === false){
    useEffect(() => {
        setTimeout(() => {
            console.log('time')
            // setCount(eggCount + 1);
            setUserData(prevState => ({
                ...prevState,
                eggs: userData.eggs + 1
            }))
            document.getElementById("egggg").setAttribute("src", egg)
            // eggArr.push({image: egg, xpos: 100, ypos: 100, width: 100, height: 100})
        }, 5000)
        API.updateEggs(userData.id, userData.eggs).then(() => {
            console.log("data updated")
        })
    }, [userData.eggs])

    console.log("USER DATA", userData)
    return (
        <div style={{ width: "100vw", height: "100vh", overflow: "hidden" }} ref={windowdim}>
            <p className="egg-counter">Number of eggs: {userData.eggs}</p>
            
            <img id="egggg" src="" onClick={spawnEgg}></img>

            <button onClick={spawnFood}>Feed!</button>

            <h2 className="chick-name">Say hello to: {userData.chicken.name}</h2>


            {/* <motion.div animate={{ y: 100 }} transition={{ yoyo: Infinity }} id="chickenCont"> */}
            <motion.div animate={{ rotate: [-90, 0, -90, 0] }} transistion={{ type: 'spring', bounce: 2, }} id="chickenCont">
                <img src={require("../assets/floppy-bird.png")} alt="yicken" className="chicken" ></img>
                <motion.img 
                    // drag
                    // dragConstraints={windowdim}
                    initial={{ y: -500 }}
                    src={userHat} className="draggables" id="hat">
                </motion.img>
                <motion.img 
                    // drag
                    // dragConstraints={windowdim}
                    initial={{ y: -285 }}
                    src={userShoes} className="draggables" id="shoe">
                </motion.img>
                <motion.img 
                    // drag
                    // dragConstraints={windowdim}
                    initial={{ y: -600 }}
                    src={userArms} className="draggables" id="arm">
                </motion.img>
            </motion.div>
            <motion.img id="wheaties" src="" initial={{ x: 350, y: -1000 }} animate={{ x: 350, y: -500 }} transition={{ duration: 0.75, type: 'spring', bounce: 0.25 }}></motion.img>

        </div>

    )
    
}
